### PR TITLE
Fix/kustomize for argocd

### PR DESCRIPTION
**Pull request by goern**
## This introduces a breaking change

- [ ] Yes
- [X] No

## This Pull Request implements

this is a cleanup so that we can deploy thoth-ci via argocd

### CODE REVIEW

**Comment by goern** [comment]
> @goern can we add `tasks/*` in kustomize resource?

like all of the files in that directory?

**Comment by harshad16** [comment]
> > @goern can we add `tasks/*` in kustomize resource?
> 
> like all of the files in that directory?

yeah like including all files.

**Comment by goern** [comment]
> > > @goern can we add `tasks/*` in kustomize resource?
> > 
> > 
> > like all of the files in that directory?
> 
> yeah like including all files.

hmm, I guess that is not how a declarative tool works... "get whatever might be in that directory" :)

**Comment by harshad16** [comment]
> > > > @goern can we add `tasks/*` in kustomize resource?
> > > 
> > > 
> > > like all of the files in that directory?
> > 
> > 
> > yeah like including all files.
> 
> hmm, I guess that is not how a declarative tool works... "get whatever might be in that directory" :)

:grimacing:  got it

**Pull request merged**
